### ISSUE TITLE
Original code has been relicensed

### ISSUE THREAD

**Issue by domenzain** [Theano/Theano_lgpl#1]
Hi @nouiz,

It seems Christian Borgelt has relicensed the original code as MIT License.

You can get the latest source package `apriori.zip` from http://www.borgelt.net/apriori.html and in it, under the `math` directory.
The relevant file is unchanged.

Would you consider relicensing your own contributions for inclusion in Theano directly?

**Comment by nouiz** [comment]
Due to https://groups.google.com/forum/#!msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ, I won't do it.

If someone is ready to port it and make a PR to Theano, I'll review it.

thanks for the suggestion.

**Comment by twiecki** [comment]
@nouiz I think the question is just if you would relicense your code, we'd do the rest.

**Comment by domenzain** [comment]
@nouiz , as @twiecki mentions above I request your consent to use your package as it is under BSD 3-clause license (Theano) or MIT license instead of LGPL.

I think the original reason for this package to be separate from Theano was the LGPL license in the original code. As the original code has been relicensed, if you relicense your own contributions then this entire module is immediately useable under the same terms as Theano itself.

**Comment by nouiz** [comment]
I just pushed a LICENSE.txt file that make it clear this repo is under BSD 3-clauses, but the copied file have its own license.

If you want to move that to Theano, it would be better to start from a new copy of the original file. Then apply my diff to it. Make that separate commit. This way if there is small difference to the file, we will be safe.

**Comment by domenzain** [comment]
Great, thank you!

For reference I'll reapply your commits on top of the original MIT licensed code  at https://github.com/domenzain/Theano_chi2sf

**Comment by twiecki** [comment]
Fantastic, much appreciated!

@domenzain What's your plan with this?

**Comment by domenzain** [comment]
I have wrapped the other gamma functions in the original C code. These will help provide CDF functions for the Gamma family of distributions.

Now that they are wrapped and that the code is either MIT or BSD 3-clause, I guess they could either stay in a separate package or be put alongside other tensor functions in theano. Any preference?

**Comment by twiecki** [comment]
@domenzain But where do you think they should live? Theano proper?

**Comment by domenzain** [comment]
I think that would be best.
In theano.tensor probably.

**Comment by nouiz** [comment]
More in theano/scalar I think.
Make a new file, similar to basic_scipy.py

**Comment by domenzain** [comment]
Thank you for the guidance. I'll put them there and make a pull request.
